title: Information About Me
author: Arun Ramanathan
email: aramanathan@ebnet.org
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Information about Arun Ramanathan

# social links
twitter_username: ArunRamanathan6 # DO NOT include the @ character, or else the build will fail!
github_username:  ArunRamanathan1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
